[package]
name = "azik_generator"
license = "MIT"
authors = ["Maki <maki111000664455@gmail.com>"]
description = "Generate Google IME Setting file"
version = "0.1.5"
edition = "2021"

[dependencies]
generate_kana_table = "0.1.1"
